{
 "title": "Pi Cluster",
 "description": "Alerts for Linux Nodes using prometheus and node_exporter. You can have alerts for Disk space, CPU and Memory. Also added a log of alerts and alert status.",
 "tags": [
  "alerts",
  "linux"
 ],
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "5s",
 "panels": [
  { "title": "Alerts Status", "type": "alertlist", "gridPos": { "h": 5, "w": 5, "x": 0, "y": 0 } },
  { "title": "Alerts Log", "type": "alertlist", "gridPos": { "h": 5, "w": 19, "x": 5, "y": 0 } },
  {
   "title": "CPU Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100 - (avg by (instance) (irate(node_cpu_seconds_total{mode=\"idle\"}[1m])) * 100)",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Memory Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 12 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100*(node_memory_MemTotal_bytes - node_memory_MemFree_bytes - node_memory_Buffers_bytes - node_memory_Cached_bytes) / node_memory_MemTotal_bytes ",
     "legendFormat": "{{instance}}"
    }
   ]
  },
  {
   "title": "Disk Usage",
   "type": "graph",
   "gridPos": { "h": 7, "w": 24, "x": 0, "y": 19 },
   "yaxes": [
    { "format": "percent" }
   ],
   "targets": [
    {
     "expr": "100.0 - 100 * ((node_filesystem_avail_bytes / 1000 / 1000 ) / (node_filesystem_size_bytes  / 1024 / 1024))",
     "legendFormat": "{{instance}} - {{mountpoint}}"
    }
   ]
  }
 ]
}